# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AuthorisationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, self):
        self.setObjectName("self")
        self.resize(800, 600)
        self.setStyleSheet("background-color:rgb(210,210,210);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 121, 61))
        self.label.setStyleSheet("color:rgb(0,0,0);font:16pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 121, 61))
        self.label_2.setStyleSheet("color:rgb(0,0,0);font:16pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(10, 512, 111, 71))
        self.button_quit.setStyleSheet("background-color:rgb(255,255,255);color:rgb(0,0,0);font:16pt \"Arial\";")
        self.button_quit.setObjectName("button_quit")
        self.button_enter = QtWidgets.QPushButton(self.centralwidget)
        self.button_enter.setGeometry(QtCore.QRect(300, 270, 161, 71))
        self.button_enter.setStyleSheet("background-color:rgb(255,255,255);color:rgb(0,0,0);font:16pt \"Arial\";")
        self.button_enter.setObjectName("button_enter")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(230, 70, 401, 41))
        self.lineEdit_login.setStyleSheet("background-color:rgb(255,255,255);color:rgb(0,0,0);font:16pt \"Arial\";")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(230, 140, 401, 41))
        self.lineEdit_password.setStyleSheet("background-color:rgb(255,255,255);color:rgb(0,0,0);font:16pt \"Arial\";")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(270, 220, 241, 41))
        self.checkBox.setStyleSheet("font:16pt \"Arial\";")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.setCentralWidget(self.centralwidget)

        QtCore.QMetaObject.connectSlotsByName(self)

    
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Окно авторизации"))
        self.label.setText(_translate("self", "Логин:"))
        self.label_2.setText(_translate("self", "Пароль:"))
        self.button_quit.setText(_translate("self", "ВЫХОД"))
        self.button_enter.setText(_translate("self", "Войти"))
        self.checkBox.setText(_translate("self", "Запомнить меня"))
