# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 454)
        MainWindow.setStyleSheet("background-color: rgb(155, 200, 165);\n")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 401, 41))
        self.label.setStyleSheet("color:rgb(0,0,0);font:18pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 50, 401, 301))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 75))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 384, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout.setContentsMargins(12, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")

        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(350, 50))
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        for i in range(1,11):
            button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
            button.setMinimumSize(QtCore.QSize(350,50))
            button.setStyleSheet("background-color:rgb(255,255,255);color:rgb(0,0,0);font:18pt \"Arial\";")
            self.formLayout.setWidget(i, QtWidgets.QFormLayout.LabelRole, button)
            self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(20, 360, 150, 70))
        self.button_quit.setStyleSheet("background-color: rgb(255,255,255);color:rgb(0,0,0);font: 18pt \"Arial\";")
        self.button_quit.setObjectName("button_quit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Плеер"))
        self.label.setText(_translate("MainWindow", "Выберите трек"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.button_quit.setText(_translate("MainWindow", "Выйти"))

import sys
app = QtWidgets.QApplication(sys.argv)
w = QtWidgets.QMainWindow()
window = Ui_MainWindow()
window.setupUi(w)

sys.exit(app.exec())